<?php /* @var Rejoiner_Acr_Block_Snippets $this */ ?>
<?php /** @var Rejoiner_Acr_Helper_Data $rejoinerHelper */
    $rejoinerHelper = $this->helper('rejoiner_acr');
?>
<script type="text/javascript">
    //<![CDATA[
    var _rejoiner = _rejoiner || [];
    _rejoiner.push(["setAccount", "<?php echo $rejoinerHelper->getRejoinerSiteId(); ?>"]);
    _rejoiner.push(["setDomain", "<?php echo $rejoinerHelper->getDomain(); ?>"]);

    <?php if ($rejoinerHelper->getTrackNumberEnabled()): ?>
        _rejoiner.push(["trackNumbers"]);
    <?php endif; ?>
    <?php if ($rejoinerHelper->getPersistFormsEnabled()): ?>
        _rejoiner.push(["persistForms"]);
    <?php endif; ?>
    (function() {
        var s = document.createElement('script'); s.type = 'text/javascript';
        s.async = true; s.src = 'https://s3.amazonaws.com/rejoiner/js/v3/t.js';
        var x = document.getElementsByTagName('script')[0]; x.parentNode.insertBefore(s, x);
    })();
    <?php if (Mage::helper('checkout/cart')->getCart()->getSummaryQty()): ?>
        <?php $items = $this->getCartItems();
             $cartData = $this->getCartData();
             $cartData .= ($this->getChildHtml('rejoiner_email'))? ' ,' . $this->getChildHtml('rejoiner_email'): '';
        ?>
        <?php if (Mage::getStoreConfig('checkout/rejoiner_acr/coupon_code')): ?>
            <?php $couponCode = $rejoinerHelper->generateCouponCode();
            $cartData .= ','.'"promo"'.':'.'"'.$couponCode.'"';?>
        <?php endif; ?>
         _rejoiner.push(["setCartData", <?php echo $cartData? "{". $cartData . "}" : ''?>]);
        <?php foreach ($items as $item): ?>
            <?php $itemsAsJson = Mage::helper('core')->jsonEncode($item); ?>
            _rejoiner.push(["setCartItem", <?php echo $itemsAsJson; ?>]);
        <?php endforeach ?>
    <?php endif ?>
    //]]>
</script>

<script type="text/javascript">
    /** removeCartItem **/
    //<![CDATA[
    <?php if ($removedItems = $rejoinerHelper->checkRemovedItem()): ?>
        <?php foreach ($removedItems as $item): ?>
        _rejoiner.push(['removeCartItem', {product_id: '<?php echo $item; ?>'}]);
        <?php endforeach; ?>
    <?php endif; ?>
    //]]>
</script>